export interface BuiltInFeed {
  title: string;
  route: string;
  type?: 'rsshub' | 'native';
}

export interface BuiltInTopic {
  name: string;
  icon: string;
  feeds: BuiltInFeed[];
}

export const BUILT_IN_TOPICS: BuiltInTopic[] = [
  {
    name: '热点时事',
    icon: 'fire',
    feeds: [
      { title: '知乎热榜', route: '/zhihu/hot' },
      { title: '知乎日报', route: '/zhihu/daily' },
      { title: '澎湃新闻', route: '/thepaper/featured' },
      { title: 'Readhub 热门', route: '/readhub/topic' },
      { title: 'V2EX 热门', route: '/v2ex/topics/hot' },
      { title: 'BBC World', route: 'https://feeds.bbci.co.uk/news/world/rss.xml', type: 'native' },
      { title: 'NYT World', route: 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', type: 'native' },
      { title: 'Foreign Policy', route: 'https://foreignpolicy.com/feed/', type: 'native' },
    ],
  },
  {
    name: '财经商业',
    icon: 'cash-multiple',
    feeds: [
      { title: '36氪快讯', route: '/36kr/newsflashes' },
      { title: '36氪深度', route: '/36kr/information/web_news' },
      { title: '华尔街见闻', route: '/wallstreetcn/news/global' },
      { title: '财新网', route: '/caixin/latest' },
      { title: '虎嗅', route: '/huxiu/article' },
      { title: '格隆汇', route: '/gelonghui/live' },
      { title: '创业邦', route: '/cyzone/news' },
      { title: '东方财富研报', route: '/eastmoney/report/strategyreport' },
      { title: 'Bloomberg Markets', route: 'https://feeds.bloomberg.com/markets/news.rss', type: 'native' },
      { title: 'Economist Finance', route: 'https://www.economist.com/finance-and-economics/rss.xml', type: 'native' },
      { title: 'NYT Business', route: 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml', type: 'native' },
      { title: 'BBC Business', route: 'https://feeds.bbci.co.uk/news/business/rss.xml', type: 'native' },
      { title: 'Stratechery', route: 'https://stratechery.com/feed/', type: 'native' },
      { title: 'Inc.', route: 'https://www.inc.com/rss', type: 'native' },
    ],
  },
  {
    name: '科技前沿',
    icon: 'chip',
    feeds: [
      { title: '少数派', route: 'https://sspai.com/feed', type: 'native' },
      { title: 'IT之家', route: '/ithome/it' },
      { title: '品玩', route: '/pingwest/status' },
      { title: '雷锋网', route: '/leiphone/newsflash' },
      { title: '爱范儿', route: 'https://www.ifanr.com/feed', type: 'native' },
      { title: 'The Verge', route: 'https://www.theverge.com/rss/index.xml', type: 'native' },
      { title: 'Ars Technica', route: 'https://feeds.arstechnica.com/arstechnica/index', type: 'native' },
      { title: 'TechCrunch', route: 'https://techcrunch.com/feed/', type: 'native' },
      { title: 'Wired', route: 'https://www.wired.com/feed/rss', type: 'native' },
      { title: 'Engadget', route: 'https://www.engadget.com/rss.xml', type: 'native' },
      { title: 'TNW', route: 'https://thenextweb.com/feed', type: 'native' },
      { title: 'ZDNet', route: 'https://www.zdnet.com/news/rss.xml', type: 'native' },
      { title: 'Fast Company', route: 'https://www.fastcompany.com/latest/rss', type: 'native' },
      { title: 'Product Hunt', route: 'https://www.producthunt.com/feed', type: 'native' },
      { title: 'BBC Tech', route: 'https://feeds.bbci.co.uk/news/technology/rss.xml', type: 'native' },
    ],
  },
  {
    name: 'AI 前沿',
    icon: 'robot',
    feeds: [
      { title: '果壳科学', route: '/guokr/scientific' },
      { title: 'DeepMind Blog', route: 'https://deepmind.google/blog/rss.xml', type: 'native' },
      { title: 'Hugging Face Blog', route: 'https://huggingface.co/blog/feed.xml', type: 'native' },
      { title: "Ben's Bites (AI)", route: 'https://www.bensbites.com/feed', type: 'native' },
      { title: 'AI News', route: 'https://buttondown.com/ainews/rss', type: 'native' },
      { title: 'Lilian Weng', route: 'https://lilianweng.github.io/index.xml', type: 'native' },
      { title: 'Colah (Neural Nets)', route: 'https://colah.github.io/rss.xml', type: 'native' },
      { title: 'Distill.pub', route: 'https://distill.pub/rss.xml', type: 'native' },
      { title: 'MIT Technology Review', route: 'https://www.technologyreview.com/feed/', type: 'native' },
      { title: 'Google Blog', route: 'https://blog.google/rss/', type: 'native' },
    ],
  },
  {
    name: '开发者',
    icon: 'code-braces',
    feeds: [
      { title: 'Solidot', route: '/solidot/www' },
      { title: '阮一峰的博客', route: 'https://feeds.feedburner.com/ruanyifeng', type: 'native' },
      { title: 'Tw93 潮流周刊', route: 'https://weekly.tw93.fun/rss.xml', type: 'native' },
      { title: 'DIYgod', route: 'https://diygod.cc/feed', type: 'native' },
      { title: 'Randy Lu', route: 'https://lutaonan.com/rss.xml', type: 'native' },
      { title: 'BYVoid', route: 'https://byvoid.com/zhs/feed.xml', type: 'native' },
      { title: 'Cat Coding', route: 'https://catcoding.me/atom.xml', type: 'native' },
      { title: 'BMPI', route: 'https://www.bmpi.dev/index.xml', type: 'native' },
      { title: 'GeekPlux', route: 'https://geekplux.com/feed.xml', type: 'native' },
      { title: '云风的博客', route: 'https://blog.codingnow.com/atom.xml', type: 'native' },
      { title: '王垠的博客', route: 'https://www.yinwang.org/atom.xml', type: 'native' },
      { title: 'Hacker News', route: 'https://hnrss.org/frontpage', type: 'native' },
      { title: 'Lobsters', route: 'https://lobste.rs/rss', type: 'native' },
      { title: 'Dev.to', route: 'https://dev.to/feed', type: 'native' },
      { title: 'GitHub Blog', route: 'https://github.blog/feed/', type: 'native' },
      { title: 'Cloudflare Blog', route: 'https://blog.cloudflare.com/rss/', type: 'native' },
      { title: 'Netflix Tech', route: 'https://netflixtechblog.com/feed', type: 'native' },
      { title: 'Meta Engineering', route: 'https://engineering.fb.com/feed/', type: 'native' },
      { title: 'Martin Fowler', route: 'https://martinfowler.com/feed.atom', type: 'native' },
      { title: 'Dan Abramov', route: 'https://overreacted.io/rss.xml', type: 'native' },
      { title: 'Julia Evans', route: 'https://jvns.ca/atom.xml', type: 'native' },
      { title: 'Simon Willison', route: 'https://simonwillison.net/atom/everything/', type: 'native' },
      { title: 'Pragmatic Engineer', route: 'https://blog.pragmaticengineer.com/rss/', type: 'native' },
      { title: 'Dan Luu', route: 'https://danluu.com/atom.xml', type: 'native' },
      { title: 'Joel on Software', route: 'https://www.joelonsoftware.com/feed/', type: 'native' },
      { title: 'Smashing Magazine', route: 'https://www.smashingmagazine.com/feed/', type: 'native' },
      { title: 'CSS-Tricks', route: 'https://css-tricks.com/feed/', type: 'native' },
      { title: 'InfoWorld', route: 'https://www.infoworld.com/feed/', type: 'native' },
    ],
  },
  {
    name: '科学探索',
    icon: 'flask',
    feeds: [
      { title: '果壳科学', route: '/guokr/scientific' },
      { title: 'Solidot', route: '/solidot/www' },
      { title: 'Nature', route: 'https://www.nature.com/nature.rss', type: 'native' },
      { title: 'Science', route: 'https://www.science.org/rss/news_current.xml', type: 'native' },
      { title: 'Quanta Magazine', route: 'https://www.quantamagazine.org/feed/', type: 'native' },
      { title: 'ScienceDaily', route: 'https://www.sciencedaily.com/rss/all.xml', type: 'native' },
      { title: 'NYT Science', route: 'https://rss.nytimes.com/services/xml/rss/nyt/Science.xml', type: 'native' },
      { title: 'BBC Science', route: 'https://feeds.bbci.co.uk/news/science_and_environment/rss.xml', type: 'native' },
      { title: 'IEEE Spectrum', route: 'https://spectrum.ieee.org/feeds/feed.rss', type: 'native' },
      { title: 'The Conversation', route: 'https://theconversation.com/articles.atom', type: 'native' },
      { title: 'Aeon', route: 'https://aeon.co/feed.rss', type: 'native' },
    ],
  },
  {
    name: '深度思考',
    icon: 'book-open-variant',
    feeds: [
      { title: '南方周末', route: '/infzm/1' },
      { title: '得到精选', route: '/dedao/list/年度日更' },
      { title: '机核', route: 'https://www.gcores.com/rss', type: 'native' },
      { title: '阮一峰的博客', route: 'https://feeds.feedburner.com/ruanyifeng', type: 'native' },
      { title: '豆瓣新书速递', route: '/douban/book/latest' },
      { title: '豆瓣电影周榜', route: '/douban/movie/weekly' },
      { title: 'Wait But Why', route: 'https://waitbutwhy.com/feed', type: 'native' },
      { title: 'Paul Graham', route: 'https://paulgraham.com/rss.html', type: 'native' },
      { title: 'Farnam Street', route: 'https://fs.blog/feed/', type: 'native' },
      { title: 'Naval Ravikant', route: 'https://nav.al/feed', type: 'native' },
      { title: 'Seth Godin', route: 'https://seths.blog/feed/', type: 'native' },
      { title: 'Longreads', route: 'https://longreads.com/feed/', type: 'native' },
      { title: 'Literary Hub', route: 'https://lithub.com/feed/', type: 'native' },
      { title: 'Aeon Essays', route: 'https://aeon.co/feed.rss', type: 'native' },
      { title: 'xkcd', route: 'https://xkcd.com/atom.xml', type: 'native' },
    ],
  },
  {
    name: '创投圈',
    icon: 'rocket-launch',
    feeds: [
      { title: '虎嗅', route: '/huxiu/article' },
      { title: '创业邦', route: '/cyzone/news' },
      { title: '36氪深度', route: '/36kr/information/web_news' },
      { title: 'Stratechery', route: 'https://stratechery.com/feed/', type: 'native' },
      { title: "Lenny's Newsletter", route: 'https://www.lennysnewsletter.com/feed', type: 'native' },
      { title: 'Not Boring', route: 'https://www.notboring.co/feed', type: 'native' },
      { title: 'Platformer', route: 'https://www.platformer.news/rss/', type: 'native' },
      { title: 'The Information', route: 'https://www.theinformation.com/feed', type: 'native' },
    ],
  },
  {
    name: '信息安全',
    icon: 'shield-lock',
    feeds: [
      { title: 'Krebs on Security', route: 'https://krebsonsecurity.com/feed/', type: 'native' },
      { title: 'Schneier on Security', route: 'https://www.schneier.com/feed/atom/', type: 'native' },
      { title: 'Cloudflare Blog', route: 'https://blog.cloudflare.com/rss/', type: 'native' },
    ],
  },
  {
    name: '加密货币',
    icon: 'bitcoin',
    feeds: [
      { title: '金色财经', route: '/jinse/lives' },
      { title: '36氪快讯', route: '/36kr/newsflashes' },
    ],
  },
];

export const DEFAULT_RSSHUB_URL = 'http://linghua.icu:1200';
