export interface BuiltInFeed {
  title: string;
  route: string;
}

export interface BuiltInTopic {
  name: string;
  icon: string;
  feeds: BuiltInFeed[];
}

export const BUILT_IN_TOPICS: BuiltInTopic[] = [
  {
    name: '财经',
    icon: 'cash-multiple',
    feeds: [
      { title: '36氪快讯', route: '/36kr/newsflashes' },
      { title: '36氪资讯', route: '/36kr/information/web_news' },
      { title: '华尔街见闻', route: '/wallstreetcn/news/global' },
      { title: '华尔街见闻·要闻', route: '/wallstreetcn/news/shares' },
      { title: '财新网', route: '/caixin/latest' },
      { title: '第一财经', route: '/yicai/brief' },
      { title: '东方财富研报', route: '/eastmoney/report/strategyreport' },
      { title: '格隆汇', route: '/gelonghui/live' },
      { title: '新浪财经头条', route: '/sina/finance/top' },
      { title: '证券时报', route: '/stcn/news/index' },
      { title: '经济观察报', route: '/eeo/yaowen' },
      { title: '财经杂志', route: '/caijing/roll' },
      { title: 'FT中文网', route: '/ft/chinese/hotstoryby7day' },
      { title: '界面新闻·商业', route: '/jiemian/list/4' },
      { title: '投中网', route: '/chinaventure/news/78' },
    ],
  },
  {
    name: '科技',
    icon: 'chip',
    feeds: [
      { title: '少数派', route: '/sspai/index' },
      { title: '少数派 Matrix', route: '/sspai/matrix' },
      { title: 'IT之家', route: '/ithome/it' },
      { title: 'Solidot', route: '/solidot/www' },
      { title: '开源中国', route: '/oschina/news' },
      { title: '虎嗅', route: '/huxiu/article' },
      { title: 'Readhub', route: '/readhub/topic' },
      { title: '爱范儿', route: '/ifanr/app' },
      { title: '极客公园', route: '/geekpark/breakingnews' },
      { title: '品玩', route: '/pingwest/status' },
      { title: '机器之心', route: '/jiqizhixin/daily' },
      { title: '量子位', route: '/qbitai/category/资讯' },
      { title: 'TechCrunch', route: '/techcrunch' },
      { title: 'The Verge', route: '/theverge' },
      { title: 'Ars Technica', route: '/arstechnica/index' },
      { title: 'Wired', route: '/wired/tag/ai' },
      { title: 'MIT科技评论', route: '/mittrchina/newest' },
    ],
  },
  {
    name: '热榜',
    icon: 'fire',
    feeds: [
      { title: '知乎热榜', route: '/zhihu/hot' },
      { title: '知乎日报', route: '/zhihu/daily' },
      { title: '微博热搜', route: '/weibo/search/hot' },
      { title: '百度热搜', route: '/baidu/hot' },
      { title: '今日头条热榜', route: '/toutiao/hot' },
      { title: 'B站热搜', route: '/bilibili/hot-search' },
      { title: '豆瓣正在上映', route: '/douban/movie/playing' },
      { title: '什么值得买热榜', route: '/smzdm/ranking/pinlei/11/0' },
      { title: '酷安热榜', route: '/coolapk/hot' },
      { title: 'V2EX热门', route: '/v2ex/topics/hot' },
      { title: 'GitHub Trending', route: '/github/trending/daily/all' },
      { title: 'Product Hunt', route: '/producthunt/today' },
      { title: 'Hacker News', route: '/hackernews/best' },
    ],
  },
  {
    name: '深度新闻',
    icon: 'newspaper-variant-outline',
    feeds: [
      { title: '澎湃新闻', route: '/thepaper/featured' },
      { title: '南方周末', route: '/infzm/1' },
      { title: '界面新闻', route: '/jiemian/list/4' },
      { title: '端传媒', route: '/initium/latest/zh-hans' },
      { title: '纽约时报中文', route: '/nytimes/morning_post' },
      { title: 'BBC中文', route: '/bbc/zhongwen/simp' },
      { title: '路透社', route: '/reuters/world' },
      { title: '联合早报', route: '/zaobao/realtime/china' },
      { title: '新华社', route: '/xinhuanet/news' },
      { title: '央视新闻', route: '/cctv/world' },
      { title: '环球时报', route: '/globaltimes' },
      { title: '经济学人', route: '/economist/latest' },
    ],
  },
  {
    name: '加密货币',
    icon: 'bitcoin',
    feeds: [
      { title: '金色财经', route: '/jinse/lives' },
      { title: 'CoinDesk', route: '/coindesk/consensus-magazine' },
      { title: '律动BlockBeats', route: '/theblockbeats/newsflash' },
      { title: '吴说区块链', route: '/wublock/index' },
      { title: 'Foresight News', route: '/foresightnews/article' },
      { title: 'PANews', route: '/panewslab/news' },
      { title: 'Decrypt', route: '/decrypt/news' },
      { title: 'The Block', route: '/theblock/news' },
    ],
  },
  {
    name: '创投',
    icon: 'rocket-launch',
    feeds: [
      { title: '36氪创投', route: '/36kr/newsflashes' },
      { title: '虎嗅', route: '/huxiu/article' },
      { title: '格隆汇', route: '/gelonghui/live' },
      { title: '投中网', route: '/chinaventure/news/78' },
      { title: '创业邦', route: '/cyzone/news' },
      { title: 'TechCrunch', route: '/techcrunch' },
      { title: 'Y Combinator Blog', route: '/ycombinator/blog' },
      { title: 'Product Hunt', route: '/producthunt/today' },
      { title: '硅星人', route: '/guixingren' },
      { title: '甲子光年', route: '/agiclass/latest' },
    ],
  },
  {
    name: '影视娱乐',
    icon: 'movie-open',
    feeds: [
      { title: '豆瓣正在上映', route: '/douban/movie/playing' },
      { title: '豆瓣电影Top250', route: '/douban/movie/weekly' },
      { title: '豆瓣新书速递', route: '/douban/book/latest' },
      { title: '豆瓣小组精选', route: '/douban/group/explore' },
      { title: '时光网新闻', route: '/mtime/news' },
      { title: 'B站排行榜', route: '/bilibili/ranking/0/3/1' },
      { title: '网易云音乐热歌榜', route: '/163/music/playlist/3778678' },
      { title: '煎蛋', route: '/jandan/top' },
    ],
  },
  {
    name: '知识学习',
    icon: 'book-open-variant',
    feeds: [
      { title: '知乎热榜', route: '/zhihu/hot' },
      { title: '知乎日报', route: '/zhihu/daily' },
      { title: '少数派', route: '/sspai/index' },
      { title: '果壳科学', route: '/guokr/scientific' },
      { title: 'Readhub', route: '/readhub/topic' },
      { title: 'Nature News', route: '/nature/news' },
      { title: 'MIT News', route: '/mit/news' },
      { title: '中国科学报', route: '/sciencenet/blog' },
      { title: 'TED Talks', route: '/ted/talks' },
      { title: '得到', route: '/dedao/list/年度日更' },
      { title: 'Medium Top', route: '/medium/topic/technology' },
    ],
  },
  {
    name: '国际视野',
    icon: 'earth',
    feeds: [
      { title: '华尔街见闻·全球', route: '/wallstreetcn/news/global' },
      { title: '澎湃新闻', route: '/thepaper/featured' },
      { title: '南方周末', route: '/infzm/1' },
      { title: '纽约时报中文', route: '/nytimes/morning_post' },
      { title: 'BBC中文', route: '/bbc/zhongwen/simp' },
      { title: '路透社', route: '/reuters/world' },
      { title: '联合早报', route: '/zaobao/realtime/china' },
      { title: '经济学人', route: '/economist/latest' },
      { title: 'FT中文网', route: '/ft/chinese/hotstoryby7day' },
      { title: '日经亚洲', route: '/nikkei/asia' },
    ],
  },
  {
    name: '开发者',
    icon: 'code-braces',
    feeds: [
      { title: '开源中国', route: '/oschina/news' },
      { title: 'Solidot', route: '/solidot/www' },
      { title: 'Readhub', route: '/readhub/topic' },
      { title: 'IT之家', route: '/ithome/it' },
      { title: 'Hacker News', route: '/hackernews/best' },
      { title: 'GitHub Trending', route: '/github/trending/daily/all' },
      { title: '掘金前端', route: '/juejin/category/frontend' },
      { title: '掘金后端', route: '/juejin/category/backend' },
      { title: '掘金AI', route: '/juejin/category/ai' },
      { title: 'V2EX热门', route: '/v2ex/topics/hot' },
      { title: 'InfoQ', route: '/infoq/recommend' },
      { title: 'CSS-Tricks', route: '/css-tricks' },
      { title: 'Dev.to', route: '/dev.to/top' },
      { title: 'Smashing Magazine', route: '/smashingmagazine/articles' },
    ],
  },
  {
    name: 'AI与人工智能',
    icon: 'robot',
    feeds: [
      { title: '机器之心', route: '/jiqizhixin/daily' },
      { title: '量子位', route: '/qbitai/category/资讯' },
      { title: 'MIT科技评论', route: '/mittrchina/newest' },
      { title: 'OpenAI Blog', route: '/openai/blog' },
      { title: 'Google AI Blog', route: '/google/ai/blog' },
      { title: 'Hugging Face Blog', route: '/huggingface/blog' },
      { title: 'AI前线', route: '/infoq/ai' },
      { title: 'Wired AI', route: '/wired/tag/ai' },
      { title: 'The Verge AI', route: '/theverge/ai' },
      { title: 'Ars Technica AI', route: '/arstechnica/ai' },
    ],
  },
  {
    name: '生活方式',
    icon: 'coffee',
    feeds: [
      { title: '少数派', route: '/sspai/index' },
      { title: '什么值得买', route: '/smzdm/ranking/pinlei/11/0' },
      { title: '下厨房本周最受欢迎', route: '/xiachufang/popular/hot' },
      { title: '豆瓣小组精选', route: '/douban/group/explore' },
      { title: '简书热门', route: '/jianshu/trending/weekly' },
      { title: '小红书热门', route: '/xiaohongshu/explore' },
      { title: '即刻热门', route: '/jike/topic/text/553870e8e4b0cafb0a1bef68' },
      { title: '好奇心日报', route: '/qdaily/notch' },
    ],
  },
];

export const DEFAULT_RSSHUB_URL = 'http://linghua.icu:1200';
